spring:
  application:
    name: lucky-tweet-api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful

jwt:
  expiration: 604800000

cookie:
  max-age: 604800
